import { Geist, Geist_Mono } from "next/font/google";More actions
import "bootstrap/dist/css/bootstrap.min.css";
import "./globals.css";

const geistSans = Geist({
@@ -12,7 +13,7 @@ const geistMono = Geist_Mono({
});

export const metadata = {
  title: "Create Next App",
  title: "Portfoilo - Ekta Mattar",
  description: "Generated by create next app",
};